[build]
builder = "nixpacks"

[build.watchPatterns]
includes = ["**/*.php", "**/*.js", "**/*.jsx", "**/*.css"]

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
